##
# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##

version: '3'
services:
  sbk:
    build:
      context: .
      dockerfile: ./dockers/sbk
    container_name: sbk
    hostname: sbk
    expose:
      - 9718
    ports:
      - "9718:9718"